export const USEFULL_LINKS = [
  " https://justinrhodes1.github.io/react-power-tooltip/",
  "https://www.syncfusion.com/react-ui-components/react-tooltip",
  " https://blog.logrocket.com/how-to-use-svgs-in-react/",
  " https://blog.logrocket.com/validating-react-component-props-with-prop-types-ef14b29963fc/",
  " https://medium.com/@ayabellazreg/make-a-simple-shopping-cart-app-using-react-redux-1-3-fefde93e80c7",
  " https://betterprogramming.pub/12-front-end-developer-websites-to-bookmark-294634734a02",
  " https://vhudyma-blog.eu/detect-mobile-device-in-react/",
  " https://dev.to/keefdrive/create-react-app-vs-vite-2amn",
  " https://www.toptal.com/front-end/how-to-build-css-only-smart-layouts-with-flexbox",
  " https://w3collective.com/airtable-api-react/",
  " https://avvvatars.com",
  " https://blog.logrocket.com/how-to-make-http-requests-like-a-pro-with-axios/",
  " https://www.digitalocean.com/community/tutorials/understanding-date-and-time-in-javascript",
  " https://freefrontend.com/css-tables/",
  "https://github.com/react-navigation/react-navigation/issues/717",
  " https://blog.logrocket.com/intercepting-javascript-fetch-api-requests-responses/#:~:text=Interceptors%20are%20code%20blocks%20that,authentication%2C%20logging%2C%20and%20more",
  " https://www.cronj.com/blog/what-are-http-requests-and-response/",
  "https://blog.logrocket.com/using-axios-set-request-headers/",
  "https://www.netguru.com/blog/react-native-debugger-tutorial",
  "https://chir.ag/projects/name-that-color/#E19999",
  "https://www.youtube.com/channel/UC_ax8-CBuZ3ltn8x69Di4MA/playlists",
  "https://heroicons.com/",
  " https://kentcdodds.com/courses",
  "https://code.visualstudio.com/docs/typescript/typescript-debugging",
  "https://www.typescriptlang.org/docs/handbook/compiler-options.html",
  "https://www.typescriptlang.org/docs/handbook/tsconfig-json.html",
  " https://uxdesign.cc/ui-cheat-sheet-accordions-3e88f0d4dfee",
  "https://css-tricks.com/quoting-in-html-quotations-citations-and-blockquotes",
  " https://blog.logrocket.com/implement-recaptcha-react-application/",
  "https://felixgerschau.com/react-hooks-form-validation-typescript/",
  " https://ricardometring.com/css-class-inside-other-class",
  "https://codebeautify.org/px-to-percent-converter",
  " https://chir.ag/projects/name-that-color/#116EEB",
  " https://www.frontendmentor.io/challenges",
  " https://chir.ag/projects/name-that-color/#116EEB"
];
